apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          image: jmxo/com.movieexample.rating:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: rating
