apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: jmxo/com.movieexample.movie:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: movie
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8081
  selector:
    app: movie
